# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b943084acfa47245f1be54c48c0819e"
application_url = "https://wint-inventory-app.vercel.app"
embedded = true
name = "wint-inventory-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_inventory,read_locations"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://wint-inventory-app.vercel.app/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
